#pragma once
#include <3ds.h>

#define SOC_ALIGN 0x1000
#define SOC_BUFFERSIZE 0x100000
#define MAX_INK_LIMIT 2000
#define MAX_STROKES 500
#define MAX_UNDO_STEPS 30
#define DRAW_THRESHOLD 2.0f
#define MAX_PAYLOAD_SIZE 200000
#define MAX_MESSAGES 30
#define MAX_TEXT_LENGTH 150
#define CHARS_PER_LINE 35
#define MAX_ACTIVE_USERS 50
#define LOBBY_MAX_USERS 18
#define SCROLL_SPEED 12

#define BAN_DURATION_SECONDS (48 * 60 * 60)
#define MAC_BUFFER_SIZE 20

#define DRAWING_AREA_TOP 25
#define DRAWING_AREA_BOTTOM 151
#define DRAWING_AREA_HEIGHT 240
#define DRAWING_PREVIEW_HEIGHT 125
#define TOOLBAR_Y_START 212
#define TOOLBAR_HEIGHT 28
#define MESSAGE_BOTTOM_PADDING 10
#define SCROLL_BAR_WIDTH 10
#define SCROLL_BAR_X 0

#define COLOR_BAR_Y 153
#define COLOR_BTN_SIZE 32
#define COLOR_BTN_SPACING 2
#define COLOR_BTN_START_X ((320 - (9 * (COLOR_BTN_SIZE + COLOR_BTN_SPACING) - COLOR_BTN_SPACING)) / 2)

#define SECOND_BAR_Y 186
#define SECOND_BTN_SIZE 32
#define SECOND_BTN_SPACING 4
#define SECOND_BTN_START_X ((320 - (6 * (SECOND_BTN_SIZE + SECOND_BTN_SPACING) - SECOND_BTN_SPACING)) / 2)

#define CATEGORY_COUNT 7
#define MAX_SUB_ROOMS 7

#define NTP_SERVER "pool.ntp.org"
#define NTP_PORT 123
#define NTP_TIMEOUT_MS 3000
#define NTP_SYNC_INTERVAL_MS (6 * 60 * 60 * 1000)
#define NTP_TIMESTAMP_DELTA 2208988800ull

#define ERASER_SIZE_COUNT 3
#define PEN_SIZE_COUNT 3
#define NUM_USER_COLORS 8

extern int SUB_ROOM_COUNTS[CATEGORY_COUNT];
extern const char* ROOM_NAMES[CATEGORY_COUNT];
extern const char* ROOM_DESCRIPTIONS[CATEGORY_COUNT];
extern const char* SUB_ROOM_NAMES[CATEGORY_COUNT][MAX_SUB_ROOMS];
extern const u32 USER_COLORS[NUM_USER_COLORS];